### ISSUE TITLE
React to sleep log

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#39]
**Is your feature request related to a problem? Please describe.**
We want to be able to encourage people in the early-to-sleep channel to keep up with the habit!

**Describe the solution you'd like**
When a post in the early-to-sleep channel includes the words "sleep log", Horace should react with the bed (🛏) emoji.

**Additional context**
Make sure that this only works in the early-to-sleep club.

**Comment by steventnorris** [comment]
It has been noted by kugoi and wordvalkyrie that the sleep reaction is not occurring for all instances of "Sleep Log". It's possible this is due to some sort of formatting issue. I know wordvalkyrie had theirs underlined. We may just need to add some extra checks here for what triggers the reaction.

**Comment by steventnorris** [comment]
https://github.com/Knights-Of-Academia/horace/issues/80
Bug report here
