### ISSUE TITLE
Command with info on how to contribute

### ISSUE THREAD

**Issue by Moesgaarda** [knights-of-academia/horace#56]
**Is your feature request related to a problem? Please describe.**
Now that Horace is released, it would be great with a !contribute (!github) command with info on how to help with Horace.

**Describe the solution you'd like**
It should include a link to the github, and a brief description on how to help out by either suggesting features, reporting bugs or even participating by coding.

**Describe alternatives you've considered**
Could just be a link to some hosted markdown files on how to help out, if the text is too long to include in the message.

**Additional context**
Should be understandable by non-programmers!

**Comment by cosmiccdev** [comment]
I can take this one!

**Comment by cosmiccdev** [comment]
I got a quick command up in cosmiccdev:contribute, if anyone wants to take a quick look at it. I basically just copied the similar functions of the raid command with the new text and command. Couple of quick questions for the more experienced Horace devs:
- Is there a better formatting method you'd like to use rather than just a long single line of text?
- How many comments should be added to the test file?

**Comment by ghost** [comment]
This is a quick one that can be done now, w/ just a link to the Horace wiki I have started. I can take it over once other projects are done or someone else can.
