### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by grktarik** [Knights-Of-Academia/horace#57]
**Is your feature request related to a problem? Please describe.**
We used to set Specific words with !highlight add command
If anyone mentioned that word in a post (not Uppercase sensitive) we would get notified via a Horace dm.

**Describe the solution you'd like**
set Specific words with !highlight add command

**Describe alternatives you've considered**
There are no alternatives. Highlights
**Additional context**
![Highlight](https://user-images.githubusercontent.com/39960384/67156843-59126880-f32c-11e9-8ab2-b1374dcf74b9.PNG)

**Comment by grktarik** [comment]
The Highlight Message example was randomly chosen.

not a Specific statement.....

**Comment by jenspetur94** [comment]
I would like to work on this :)

**Comment by Dendrobyte** [comment]
Alright, now that chain messages is done I'll officially jump on this for my next contribution toward Horace. However, this will rely on a storage format so that data can persist across restarts. Whilst I look into that, let me know if the following works/doesn't work.

Command format: `!highlight <add/remove/list/clear> [word]`

`!highlight add [word]` - Add a word to your list of highlights
`!highlight remote [word]` - Remove a word from your list of highlights
`!highlight list` - List all words a user has highlighted
`!highlight clear` - Clear all words from your highlight list

Note to self: Store a user and all their words, also store a word and all users attributed to it.

**Comment by Dendrobyte** [comment]
This was resolved by #120
